plugin:
    name: 'martinimultimedia.table::lang.plugin.name'
    description: 'martinimultimedia.table::lang.plugin.description'
    author: MartiniMultimedia
    icon: oc-icon-beer
    homepage: ''
navigation:
    menu-item-bookings:
        label: 'martinimultimedia.table::lang.plugin.booking'
        url: martinimultimedia/table/bookings
        icon: icon-beer
        sideMenu:
            side-menu-item2:
                label: Prenotazioni
                url: martinimultimedia/table/bookings
                icon: icon-bookmark
            side-menu-item:
                label: Users
                url: martinimultimedia/table/user
                icon: icon-user
